name: Docker Image CI

on:
  push:
    branches: [ "agdsn", "agdsn-v4" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Run prepare scripts
      run: |
        bash scripts/extract_files.sh 4.2.9
        bash scripts/apply_diffs.sh

    - name: Build agdsn image
      uses: docker/build-push-action@v6
      with:
        context: ./ldap-overleaf-sl
        file: ./ldap-overleaf-sl/agdsn.Dockerfile
        push: true
        tags: ghcr.io/agdsn/ldap-overleaf-sl:${{ github.ref_name }}
        cache-from: type=gha,scope=agdsn
        cache-to: type=gha,mode=max,scope=agdsn
